name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Remove symlinks from build output
        run: find build -type l -delete
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "github-pages"
          path: build
      - name: Check build directory size
        run: du -sh build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
